#theme: jekyll-theme-midnight
#remote_theme:  brianmaierjr/long-haul
remote_theme: artemsheludko/flexible-jekyll

social:
  github: raphaelhamzagic
  #witter: brianmaierjr
  #acebook: brianmaierjr
  #email: raphaelhamzagic@gmail.com
  linkedin: raphaelhamzagic
